### ISSUE TITLE
When using own images that are not invoices gives an unknown error

### ISSUE THREAD

**Issue by maguru-louis** [katanaml/sparrow#32]
`FileNotFoundError: [Errno 2] No such file or directory: 'docs/json/claim 001.json'
Traceback:
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/Users/louis/Documents/code/Code/sparrow/sparrow/sparrow-ui/donut/main.py", line 187, in <module>
    view(Model())
File "/Users/louis/Documents/code/Code/sparrow/sparrow/sparrow-ui/donut/main.py", line 88, in view
    DataAnnotation().view(DataAnnotation.Model(), st.session_state['ui_width'], st.session_state['device_type'],
File "/Users/louis/Documents/code/Code/sparrow/sparrow/sparrow-ui/donut/views/data_annotation.py", line 146, in view
    saved_state = self.fetch_annotations(model.rects_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/louis/Documents/code/Code/sparrow/sparrow/sparrow-ui/donut/views/data_annotation.py", line 348, in fetch_annotations
    with open(rects_file, "r") as f:`

**Comment by abaranovskis-redsamurai** [comment]
Hey. 

I think you get this error because you copied images into the file system and then tried to open an image from the UI. Current flow - the user uploads an image from UI, and the required metadata (claim 001. JSON) is auto-generated. In your case, if there are only a few files - upload them from UI. If there are a lot of files:

1. Auto-generate empty JSON files for metadata with some simple script
or
2. Change the code to auto-generate metadata if it is not available. I will be happy to merge this change into the base code

Thanks,
Andrej

**Comment by maguru-louis** [comment]
Ok, i also did inference first and it worked too. Noted on this one. Is there a way to get a merged metadata for a group of files after annotating.

**Comment by abaranovskis-redsamurai** [comment]
Hey. I'm not sure. What do you mean by merged metadata?

**Comment by maguru-louis** [comment]
Right now we can download the metadata for each image/file. But during training i use a single metadata.json that has all the metadata in that set. I was hoping it could be autogenerated from the UI

**Comment by abaranovskis-redsamurai** [comment]
Yes, you should use Export Labels button in Annotations screen. Then follow the steps to start fine-tuning, provided scripts will convert data.
