### ISSUE TITLE
LLM is disabled. Using mock LLM

### ISSUE THREAD

**Issue by tribiona** [katanaml/sparrow#47]
I am getting this :

⠙ Loading documents...
⠦ Loading embedding model...
LLM is explicitly disabled. Using MockLLM.
⠋ Building index...

And I am getting json response as {} i.e. empty
Is it because of the LLM being disabled? What is the resaon for llm to be disabled and mock llm to be used?

**Comment by abaranovskis-redsamurai** [comment]
For ingest step, this message is expected. Thats because ingest doesnt use LLM, it only builds bindings.

Regarding empty {} response, I have seen this yesterday with llamaindex agent, but it works fine with haystack agent. It looks like related to some issue with latest Ollama version, with previous version it was working fine. This is on my list to check, in the meantime you can use haystack agent.
