### ISSUE TITLE
Making it work on Windows machine

### ISSUE THREAD

**Issue by hlpr3** [katanaml/sparrow#66]
Hey thanks for the great sharing !
However I'm struggling to make it work on a Windows system.
Could you please look into it and help troubleshoot WSL installation ?

Best!

**Comment by RockyNiu** [comment]
There are many issues with the direct installation on Windows. WSL would be better option to my option. 

@hlpr3 the quick way on WSL: copy the errors in copilot and ask for solutions. It's not a big deal, and jst need to install many additional packages.

**Comment by RockyNiu** [comment]
@hlpr3 there is one more things for WSL.
Since WSL is not in the same network with host, you could not directly call localhost:11434 to query ollama.
But you could easily resolve this issue by enabling [mirrored mode networking](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking).

- `wsl --update`
- Edit your WSL configuration file (.wslconfig) in your user profile directory (e.g., C:\Users\YourUsername\.wslconfig) and add the following lines:
```
[wsl2]
networkingMode = mirrored
```
- `wsl --shutdown`
- restart WSL
