### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.utilities'

### ISSUE THREAD

**Issue by ghazirecinov** [katanaml/sparrow#7]

**Comment by ghazirecinov** [comment]
@abaranovskis-redsamurai

**Comment by bogdan-fesenko** [comment]
This happens after installing some of needed libraries (detectron2 or pytesseract) because then you have 'tools' folder in the site-packages. So app tries to import from that folder.

SOLUTION:
Rename 'tools/' folder in the project and also rename all it's imports in the project files. I used tools -> tools_local
