### ISSUE TITLE
how to get sparrow key ?

### ISSUE THREAD

**Issue by habout632** [katanaml/sparrow#76]
how to get sparrow key  on the onlien demo
{
"error"
:
"No Sparrow Key provided. Please enter a Sparrow Key before submitting."
}
https://katanaml-sparrow-ui.hf.space/

**Comment by abaranovskis-redsamurai** [comment]
Online demo is supposed to be for potential customers only, send me email and describe your use case. Otherwise you can deploy and run same code on your own infra.

**Comment by maxxyme** [comment]
Hello there...

> Online demo is supposed to be for potential customers only, send me email and describe your use case. Otherwise you can deploy and run same code on your own infra.

... then you should explicitly specify it, please, because the demo is openly promoted on the homepage of the repo: https://github.com/katanaml/sparrow e.g. on the right column under "About" or below under "Sparrow UI" -> Try Sparrow UI.
And I came here via an article in French promoting this software -> https://korben.info/sparrow-outil-extraction-donnees-ia.html which itself tells anyone to try the online demo (and I don't think that's the online article about Sparrow out there...)

Besides, I'm not a "potential customer", just a curious software engineer.

**Comment by abaranovskis-redsamurai** [comment]
Hey, my message you refer to, is a bit old and it was related to deployment on Hugging Face Cloud GPU, which was very expensive to run.

Current deployment (the one you refer from About, etc.): https://sparrow.katanaml.io, runs on my local Mac Mini M4 Pro 64 GB machine. Obviously I can't make it open to anyone, otherwise machine will be simply overloaded all the time. I plan to allow open access in the future, after migration to local Nvidia GPU.

As I mention in my recent Youtube videos, anyone can send me DM or email, and I will share Sparrow key to able to test it. If you are interested, send me email to: abaranovskis@redsamuraiconsulting.com

Thanks.
